export const CHANGE_NUMBER_OF_DEVICES = "CHANGE_NUMBER_OF_DEVICES";
export const UPDATE_SEARCHED_DEVICES = "UPDATE_SEARCHED_DEVICES";
export const SEARCH = "SEARCH";
export const SELECT_DEVICE = "SELECTED_DEVICE"

export const FETCH_DEVICES_REQUEST = "FETCH_DEVICES_REQUEST";
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
